version: 1.0.{build}

skip_tags: true

build_script:
  - cmd: dotnet build
  - cmd: dotnet test -f netcoreapp2.1
  - cmd: dotnet test -f netcoreapp3.1

image: Ubuntu

test: off

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
