version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-ef
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 1s
      timeout: 5s
      retries: 60

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
    container_name: elasticsearch-ef
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512mb -Xmx512mb
    ports:
      - "9200:9200"
    mem_limit: 2g
    healthcheck:
      test: [ "CMD", "curl", "-fsSL", "http://localhost:9200/_cat/health?h=status"]
      interval: 1s
      timeout: 5s
      retries: 60

  eventstore:
    image: eventstore/eventstore:release-4.1.3
    container_name: eventstore-ef
    ports:
      - "1113:1113"
      - "2113:2113"

  postgresql:
    image: postgres:10-alpine
    container_name: postgresql-ef
    environment:
      - "POSTGRES_PASSWORD=Password12!"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 60
