version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-ef
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    container_name: elasticsearch-ef
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    mem_limit: 1g

  eventstore:
    image: eventstore/eventstore:release-4.1.3
    container_name: eventstore-ef
    ports:
      - "1113:1113"
      - "2113:2113"

  postgresql:
    image: postgres:10
    container_name: postgresql-ef
    environment:
      - "POSTGRES_PASSWORD=Password12!"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
